name: unlockr
base: core22
adopt-info: unlockr
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
slots:
  unlockr:
    interface: dbus
    bus: session
    name: com.github.jkotra.unlockr

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH

apps:
  unlockr:
    command: usr/bin/unlockr
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-status
      - raw-usb
      - optical-drive
      - removable-media
    common-id: com.github.jkotra.unlockr
    desktop: usr/share/applications/com.github.jkotra.unlockr.desktop
    
parts:
  unlockr:
    source: https://github.com/jkotra/unlockr.git
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.jkotra.unlockr.metainfo.xml]
    meson-parameters:
      - -Dprefix=/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
 #sed -e 's|Icon=com.github.jkotra.unlockr|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/com.github.jkotra.unlockr.svg|' -i data/com.github.jkotra.unlockr.desktop.in
    build-snaps:
      - cmake
    build-packages:
      - libqpdf-dev
      - qpdf
      - libqpdf28
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/unlockr/current/usr/bin/unlockr
    
